name: CI-CD-API

on:
  push:
    branches:
      - main # [set your production branch]

env:
  USERNAME:  # [set repository owner username]
  REPO:  # [set repository name]
  URL:  # [set endpoint for api]

jobs:
  ci-cd-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up private key # [set secret with your private key]
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > private.pem
          chmod 600 private.pem

      - name: Generate timestamp and canonical string
        id: generate
        run: |
          TIMESTAMP=$(date +%s)
          CANONICAL="GET\n${TIMESTAMP}\n-"
          echo "CANONICAL=$CANONICAL" >> $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      - name: Sign request
        id: sign
        run: |
          SIGNATURE=$(printf "$CANONICAL" \
            | openssl dgst -sha256 -sign private.pem \
            | base64 -w 0)
          echo "SIGNATURE=$SIGNATURE" >> $GITHUB_ENV

      - name: Send request
        run: |
          curl -v -k \
            -H "X-Username: $USERNAME" \
            -H "X-Repo: $REPO" \
            -H "X-Body: $TIMESTAMP" \
            -H "X-Sig-body: $SIGNATURE" \
            "$URL"